baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MARABARES Y MÁS'
theme="minimo"

[menu]

  # Menú principal
  [[menu.main]]
    identifier = "diabolo"
    name = "diabolo"
    url = "/diabolo"
    weight = 1

  [[menu.main]]
    identifier = "pelotas"
    name = "pelotas"
    url = "/pelotas/"
    weight = 2

  [[menu.main]]
    identifier = "yoyo"
    name = "yoyo"
    url = "/yoyo/"
    weight = 3
